image: node:14-buster

stages:
  - publish

publish:
  stage: publish
  only:
    - develop
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${DEPLOY_TOKEN}">.npmrc
    - npm publish
